
//definizioni di valori statici
//#define SDL_AUDIO_BUFFER_SIZE 1024
#define SDL_AUDIO_BUFFER_SIZE 2048

#define VIDEO_PICTURE_QUEUE_SIZE 1

#define SAMPLE_CORRECTION_PERCENT_MAX 10
#define AUDIO_DIFF_AVG_NB 20

//#define MAX_AUDIOQ_SIZE (256)
//#define MAX_VIDEOQ_SIZE (256)
#define MAX_AUDIOQ_SIZE (64)
#define MAX_VIDEOQ_SIZE (64)

#define AV_SYNC_THRESHOLD 0.01
#define AV_NOSYNC_THRESHOLD 10.0